- name: Add an APT signing key from MSFT
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true

- name: dd repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
    state: present
    update_cache: yes
  become: true

- name: Install
  ansible.builtin.package:
    name:
      - apt-transport-https
      - code
    state: present
    update_cache: true
  become: true
