# https://www.linuxbabe.com/debian/install-syncthing
- name: Install prereq packages. Https so need apt-transport-https
  package:
    name:
      - apt-transport-https 
      - gnupg2
  become: true

- name: gpg key
  apt_key:
    url: https://syncthing.net/release-key.gpg
    state: present
  become: true

- name: Add syncthing repo
  apt_repository:
    repo: "deb https://apt.syncthing.net/ syncthing stable"
    state: present
    update_cache: yes
  become: true

- name: Install syncthing
  package:
    name:
      - syncthing
  become: true

# https://docs.syncthing.net/users/autostart.html#linux
- name: Enable service if not started
  ansible.builtin.service:
    name: "sycnthing@{{ lookup('env', 'USER') }}"
    state: started
    enabled: true
  become: true
