- name: Delete the current install
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
  become: true

- name: Download the golang tar
  get_url:
    url: "https://dl.google.com/go/go{{ VERSION }}.{{ PLATFORM }}.tar.gz"
    dest: /tmp/golang.tar.gz

- name: Decompress archive
  unarchive:
    src: /tmp/golang.tar.gz
    dest: /usr/local
  become: true

- name: Add env. Probably should just put this in your shell alias.
  ansible.builtin.shell: export PATH=$PATH:/usr/local/go/bin